#!/bin/bash
# telemt (Telegram MTProxy) configuration functions

TELEMT_CONFIG_DIR="/configs/telemt"

# Generate a 32-hex MTProxy secret for a user
# Usage: telemt_generate_secret <user_id>
# Sets: TELEMT_SECRET (exported)
telemt_generate_secret() {
    local user_id="$1"
    local user_state_dir="$STATE_DIR/users/$user_id"

    # Load existing secret if available
    if [[ -f "$user_state_dir/telemt.env" ]]; then
        source "$user_state_dir/telemt.env"
        if [[ -n "${TELEMT_SECRET:-}" ]]; then
            log_info "  Loaded existing telemt secret for $user_id"
            return 0
        fi
    fi

    # Generate new 32-hex secret
    TELEMT_SECRET=$(openssl rand -hex 16)

    # Save to state
    mkdir -p "$user_state_dir"
    cat > "$user_state_dir/telemt.env" <<EOF
TELEMT_SECRET=$TELEMT_SECRET
EOF

    log_info "  Generated telemt secret for $user_id"
}

# Write telemt config.toml from accumulated user data
# Usage: telemt_write_config
# Requires: TELEMT_USERS_TOML, TELEMT_CONNS_TOML, TELEMT_IPS_TOML (accumulated strings)
telemt_write_config() {
    log_info "Generating telemt configuration..."

    ensure_dir "$TELEMT_CONFIG_DIR"

    local port="${PORT_TELEMT:-993}"
    local tls_domain="${TELEMT_TLS_DOMAIN:-dl.google.com}"

    # Tuning parameters (configurable via .env)
    # Docs: https://github.com/telemt/telemt/blob/main/docs/TUNING.en.md
    local keepalive_random="${TELEMT_KEEPALIVE_RANDOM:-true}"
    local keepalive_jitter="${TELEMT_KEEPALIVE_JITTER:-4}"
    local keepalive_interval="${TELEMT_KEEPALIVE_INTERVAL:-20}"
    local warmup_jitter="${TELEMT_WARMUP_JITTER:-200}"
    local pool_size="${TELEMT_POOL_SIZE:-12}"
    local reinit_secs="${TELEMT_REINIT_SECS:-600}"
    local hardswap="${TELEMT_HARDSWAP:-true}"
    local hardswap_delay_min="${TELEMT_HARDSWAP_DELAY_MIN:-500}"
    local hardswap_delay_max="${TELEMT_HARDSWAP_DELAY_MAX:-1200}"
    local fast_retries="${TELEMT_FAST_RETRIES:-10}"
    local backoff_base="${TELEMT_BACKOFF_BASE:-300}"
    local backoff_cap="${TELEMT_BACKOFF_CAP:-10000}"
    local stable_snapshots="${TELEMT_STABLE_SNAPSHOTS:-3}"
    local apply_cooldown="${TELEMT_APPLY_COOLDOWN:-120}"
    local stun_tcp_fallback="${TELEMT_STUN_TCP_FALLBACK:-true}"
    local api_enabled="${TELEMT_API_ENABLED:-true}"
    local api_port="${TELEMT_API_PORT:-9091}"

    cat > "$TELEMT_CONFIG_DIR/config.toml" <<EOF
# telemt configuration - generated by MoaV bootstrap
# Do not edit manually - regenerated on bootstrap
# Tuning ref: https://github.com/telemt/telemt/blob/main/docs/TUNING.en.md

[general]
use_middle_proxy = false
log_level = "normal"

# --- Anti-DPI: Traffic Randomization ---
# Randomize keepalive payload to break DPI pattern-matching signatures
me_keepalive_enabled = true
me_keepalive_interval_secs = ${keepalive_interval}
me_keepalive_jitter_secs = ${keepalive_jitter}
me_keepalive_payload_random = ${keepalive_random}

# Randomize connection warmup timing to avoid burst fingerprints
me_warmup_stagger_enabled = true
me_warmup_step_delay_ms = 500
me_warmup_step_jitter_ms = ${warmup_jitter}

# --- Connection Pool Resilience ---
# More writers = more resilience when censors kill some connections
middle_proxy_pool_size = ${pool_size}
# Periodic pool teardown/rebuild to prevent long-connection fingerprinting
me_reinit_every_secs = ${reinit_secs}
# Generation-based pool replacement (cleaner transitions)
hardswap = ${hardswap}
me_hardswap_warmup_delay_min_ms = ${hardswap_delay_min}
me_hardswap_warmup_delay_max_ms = ${hardswap_delay_max}
me_hardswap_warmup_extra_passes = 3
me_hardswap_warmup_pass_backoff_base_ms = 500
# Keep stale writers as fallback during disruption
me_pool_drain_ttl_secs = 120
me_pool_min_fresh_ratio = 0.9

# --- Fast Reconnect (survive active blocking) ---
me_reconnect_fast_retry_count = ${fast_retries}
me_reconnect_backoff_base_ms = ${backoff_base}
me_reconnect_backoff_cap_ms = ${backoff_cap}
me_reconnect_max_concurrent_per_dc = 8

# --- Config Stability (prevent flapping) ---
me_config_stable_snapshots = ${stable_snapshots}
me_config_apply_cooldown_secs = ${apply_cooldown}
proxy_secret_stable_snapshots = ${stable_snapshots}
proxy_secret_rotate_runtime = true
update_every = 300

[general.modes]
classic = false
secure = false
tls = true

[general.links]
show = "*"
public_host = "${SERVER_IP}"
public_port = ${port}

[server]
port = 993
metrics_port = 9090
metrics_whitelist = ["0.0.0.0/0"]

[[server.listeners]]
ip = "0.0.0.0"

# --- Monitoring API ---
# Docs: https://github.com/telemt/telemt/blob/main/docs/API.md
[server.api]
enabled = ${api_enabled}
listen = "0.0.0.0:${api_port}"
whitelist = ["0.0.0.0/0", "::/0"]
read_only = true
minimal_runtime_enabled = true
minimal_runtime_cache_ttl_ms = 1000
runtime_edge_enabled = true
runtime_edge_cache_ttl_ms = 1000
runtime_edge_top_n = 20
runtime_edge_events_capacity = 256

# --- STUN / NAT Detection ---
[network]
stun_use = true
stun_tcp_fallback = ${stun_tcp_fallback}

[censorship]
tls_domain = "${tls_domain}"
mask = true
tls_emulation = true
tls_front_dir = "tlsfront"

[access.users]
${TELEMT_USERS_TOML}
[access.user_max_tcp_conns]
${TELEMT_CONNS_TOML}
[access.user_max_unique_ips]
${TELEMT_IPS_TOML}
EOF

    log_info "telemt configuration written to $TELEMT_CONFIG_DIR/config.toml"
}

# Build a tg://proxy link for a user
# Usage: telemt_build_tg_link <secret>
# Returns: link on stdout
telemt_build_tg_link() {
    local secret="$1"
    local server="${SERVER_IP}"
    local port="${PORT_TELEMT:-993}"
    local tls_domain="${TELEMT_TLS_DOMAIN:-dl.google.com}"

    # Hex-encode the TLS domain
    local hex_domain
    hex_domain=$(printf '%s' "$tls_domain" | od -An -tx1 | tr -d ' \n')

    # ee prefix = fake-TLS mode
    echo "tg://proxy?server=${server}&port=${port}&secret=ee${secret}${hex_domain}"
}

# Generate telemt client instructions for a user bundle
# Usage: telemt_generate_client_instructions <user_id> <output_dir>
telemt_generate_client_instructions() {
    local user_id="$1"
    local output_dir="$2"

    # Load user's telemt secret
    local telemt_secret=""
    if [[ -f "$STATE_DIR/users/$user_id/telemt.env" ]]; then
        source "$STATE_DIR/users/$user_id/telemt.env"
        telemt_secret="$TELEMT_SECRET"
    fi

    if [[ -z "$telemt_secret" ]]; then
        log_error "No telemt secret found for $user_id"
        return 1
    fi

    local tg_link
    tg_link=$(telemt_build_tg_link "$telemt_secret")
    local https_link
    https_link=$(echo "$tg_link" | sed 's|^tg://proxy|https://t.me/proxy|')

    # Save the proxy link
    echo "$tg_link" > "$output_dir/telegram-proxy-link.txt"

    # Generate QR code of the tg:// link
    qrencode -o "$output_dir/telegram-proxy-qr.png" -s 6 "$tg_link" 2>/dev/null || true

    # Generate instructions
    cat > "$output_dir/telegram-proxy-instructions.txt" <<EOF
# Telegram MTProxy Instructions for $user_id
# ============================================
# Connect to Telegram through your MoaV server's MTProxy.
# Uses Fake-TLS V2 for DPI evasion — traffic looks like normal HTTPS.

# -------------------------
# Quick Setup (tap/click the link):
# -------------------------

# Option 1: tg:// link (opens in Telegram app directly):
$tg_link

# Option 2: https link (opens in browser, then redirects to Telegram):
$https_link

# -------------------------
# Manual Setup:
# -------------------------

# Server: ${SERVER_IP}
# Port: ${PORT_TELEMT:-993}
# Secret: ee${telemt_secret}$(printf '%s' "${TELEMT_TLS_DOMAIN:-dl.google.com}" | od -An -tx1 | tr -d ' \n')

# iOS:
#   Settings → Data and Storage → Proxy → Add Proxy → MTProto
#   Enter server, port, and secret above

# Android:
#   Settings → Data and Storage → Proxy Settings → Add Proxy
#   Select MTProto, enter server, port, and secret

# Desktop:
#   Settings → Advanced → Connection type → Use custom proxy
#   Select MTPROTO, enter server, port, and secret

# -------------------------
# Notes:
# -------------------------
# - This proxy ONLY works for Telegram (not general internet)
# - The 'ee' prefix in the secret enables Fake-TLS mode
# - Traffic appears as HTTPS to ${TELEMT_TLS_DOMAIN:-dl.google.com}
# - No additional software needed — just the official Telegram app
# - Works on all platforms: iOS, Android, Desktop, Web
EOF

    log_info "Generated telemt instructions for $user_id"
}

# Add a user to an existing telemt config.toml
# Usage: telemt_add_user_to_config <user_id> <secret>
telemt_add_user_to_config() {
    local user_id="$1"
    local secret="$2"
    local config_file="$TELEMT_CONFIG_DIR/config.toml"

    if [[ ! -f "$config_file" ]]; then
        log_error "telemt config not found: $config_file"
        return 1
    fi

    # Check if user already exists
    if grep -q "^${user_id} = " "$config_file" 2>/dev/null; then
        log_info "User $user_id already exists in telemt config"
        return 0
    fi

    # Add user to [access.users] section
    sed -i "/^\[access\.user_max_tcp_conns\]/i ${user_id} = \"${secret}\"" "$config_file"

    # Add connection limit to [access.user_max_tcp_conns] section
    sed -i "/^\[access\.user_max_unique_ips\]/i ${user_id} = ${TELEMT_MAX_TCP_CONNS:-100}" "$config_file"

    # Add IP limit to [access.user_max_unique_ips] section (append at end)
    echo "${user_id} = ${TELEMT_MAX_UNIQUE_IPS:-10}" >> "$config_file"

    log_info "Added $user_id to telemt config"
}
